name: events_tracker
description: "A project that allows tracking different events and its repetition"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  logging: ^1.2.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  melos: ^3.4.0
  freezed: ^2.4.6

flutter:
  uses-material-design: true
