name: events_tracker
description: "A project that allows tracking different events and its repetition"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  easy_localization: ^3.0.3
  easy_logger: ^0.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  logging: ^1.2.0
  rxdart: ^0.27.7
  go_router: ^13.0.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  modal_bottom_sheet: ^3.0.0-pre
  freezed_annotation: ^2.4.1
  uuid: ^4.2.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  go_router_builder: ^2.4.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  intl: ^0.18.0
  melos: ^3.4.0
  freezed: ^2.4.6

flutter_gen:
  output: lib/generated/

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
