name: add_event
description: "Package that allows add events to app"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ui_kit: 
    path: ../ui_kit
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  equatable: ^2.0.7
  uuid: ^4.2.2
  rxdart: ^0.27.7
  collection: ^1.18.0
  json_annotation: ^4.8.1
  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
