name: calendar
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  ui_kit: 
    path: ../ui_kit
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7
  rxdart: ^0.27.7
  collection: ^1.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
